dlimon2_solutions/_code/blueprints/banking_system/__init__.py
from flask import Blueprint

bankingsystem = Blueprint('bankingsystem', __name__,
                           url_prefix='/bankingsystem',
                           template_folder='templates',)

from . import endpoints

dlimon2_solutions/_code/blueprints/currency_exchange/__init__.py
from flask import Blueprint

currencyexchange = Blueprint('currencyexchange', __name__,
                           url_prefix='/currencyexchange',
                           template_folder='templates')

from . import endpoints

dlimon2_solutions/_code/blueprints/shipping_system/__init__.py
from flask import Blueprint

shippingsystem = Blueprint('shippingsystem', __name__,
                           url_prefix='/shippingsystem',
                           template_folder='templates')

from . import endpoints

dlimon2_solutions/_code/blueprints/university_enrollment/__init__.py
from flask import Blueprint

universityenrollment = Blueprint('universityenrollment',
                                  __name__,
                                  url_prefix='/universityenrollment',
                                  template_folder='templates')

from . import endpoints

dlimon2_solutions/main.py
import os
from dotenv import load_dotenv
from flask import Flask, render_template

load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv('FLASK_SECRET_KEY')

# import blueprints
from _code.blueprints.banking_system import bankingsystem
from _code.blueprints.shipping_system import shippingsystem
from _code.blueprints.currency_exchange import currencyexchange
from _code.blueprints.university_enrollment import universityenrollment

# register blueprints
app.register_blueprint(bankingsystem)
app.register_blueprint(shippingsystem)
app.register_blueprint(currencyexchange)
app.register_blueprint(universityenrollment)


@app.route('/')
def hello():
    return render_template('hello.html')


if __name__ == '__main__':
    app.run()

dlimon2_solutions/templates/banking_system/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard - Banca Dev</title>
</head>
<body>
    <header>
        <h1>Banca Dev</h1>
    </header>
    <main>
        <h2>Dashboard</h2>
        <p>Welcome, {{username}}!</p>
        <p>Current balance: {{balance}}</p>

        {% if balance <= 0 %}
            <p>It looks like you have no funds!</p>
            <a href="{{url_for('bankingsystem.deposit')}}">Deposit money</a>
        {% else %}
            <ul>
                <li><a href="{{url_for('bankingsystem.deposit')}}">Deposit</a></li>
                <li><a href="{{url_for('bankingsystem.withdraw')}}">Withdraw</a></li>
                <li><a href="{{url_for('bankingsystem.transfer')}}">Transfer Money</a></li>
            </ul>
        {% endif %}
    </main>
    <footer>
        <a href="{{url_for('bankingsystem.logout')}}">Logout</a>
        <p>by: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/banking_system/deposit.html
<!DOCTYPE html>
<html>
<head>
    <title>Deposit - Banca Dev</title>
</head>
<body>
    <header>
        <h1>Banca Dev</h1>
    </header>
    <main>
        <h2>Deposit</h2>
        <p>Current balance: {{balance}}</p>
        <p>The deposit limit is $9999</p>
        <form action="{{url_for('bankingsystem.deposit')}}" method="post">
            <label for="bancadev_deposit_amount">Amount</label>
            <input type="number" name="bancadev_deposit_amount" id="bancadev_deposit_amount" min="1" step="0.01" required>
            <input type="submit" value="Deposit">
        </form>
        <a href="{{url_for('bankingsystem.dashboard')}}">Back to Dashboard</a>
    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/banking_system/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login - Banca Dev</title>
</head>
<body>
    <header>
        <h1>Banca Dev</h1>
    </header>
    <main>
        <form action="{{url_for('bankingsystem.login')}}" method="post">
            <label for="bancadev_username">Username:</label>
            <input type="text" id="bancadev_username" name="bancadev_username" required><br><br>
            <label for="bancadev_password">Password:</label>
            <input type="bancadev_password" id="bancadev_password" name="bancadev_password" required><br><br>
            <input type="submit" value="Login">
        </form>
    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/banking_system/transfer.html
<!DOCTYPE html>
<html>
<head>
    <title>Transfer - Banca Dev</title>
</head>
<body>
    <header>
        <h1>Banca Dev</h1>
    </header>
    <main>
        <h2>Transfer</h2>
        <p>Current balance: {{balance}}</p>
        <p>The transfer limit is $9999</p>
        <form action="{{url_for('bankingsystem.transfer')}}" method="post">
            <label for="bancadev_transfer_amount">Amount</label>
            <input type="number" name="bancadev_transfer_amount" id="bancadev_transfer_amount" min="1" step="0.01" required>
            <label for="bancadev_transfer_user">User</label>
            <input type="text" name="bancadev_transfer_user" id="bancadev_transfer_user" required>
            <input type="submit" value="Transfer">
        </form>
        <a href="{{url_for('bankingsystem.dashboard')}}">Back to Dashboard</a>
    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/banking_system/withdraw.html
<!DOCTYPE html>
<html>
<head>
    <title>Withdraw - Banca Dev</title>
</head>
<body>
    <header>
        <h1>Banca Dev</h1>
    </header>
    <main>
        <h2>Withdraw</h2>
        <p>Current balance: {{balance}}</p>
        <p>The withdraw limit is $9999</p>
        <form action="{{url_for('bankingsystem.withdraw')}}" method="post">
            <label for="bancadev_deposit_amount">Amount</label>
            <input type="number" name="bancadev_withdraw_amount" id="bancadev_withdraw_amount" min="1" step="0.01" required>
            <button type="submit">Withdraw</button>
        </form>
        <a href="{{url_for('bankingsystem.dashboard')}}">Back to Dashboard</a>
    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/currency_exchange/exchange_preview.html
<!DOCTYPE html>
<html>
<head>
    <title>Exchange - Currency Exchange</title>
</head>
<body>
    <header>
        <h1>Currency Exchange</h1>
    </header>
    <main>
        <h2>Exchange preview</h2>
        <p>From: <strong>{{origin_currency}}</strong> To: <strong>{{destination_currency}}</strong></p>
        <p>Transaction fee: 1%</p>
        
        <table>
            <tr>
                <td>Amount:</td>
                <td>{{amount}} {{origin_currency}}</td>
            </tr>
            <tr>
                <td>Pre-exchange:</td>
                <td>{{ exchange }} {{destination_currency}}</td>
            </tr>
            
            <tr>
                <td>Fee:</td>
                <td>{{ fee }} {{destination_currency}}</td>
            </tr>
            <tr>
                <td>Final exchange:</td>
                <td>{{ final_exchange }} {{destination_currency}}</td>
            </tr>
        </table>

        <p>If you want to confirm this transaction, click on Exchange</p>

        <form action="{{ url_for('currencyexchange.exchange_confirm') }}" method="post">
            <input type="hidden" name="origin_currency" value="{{origin_currency}}">
            <input type="hidden" name="destination_currency" value="{{destination_currency}}">
            <input type="hidden" name="amount" value="{{amount}}">
            <input type="hidden" name="exchange" value="{{exchange}}">
            <input type="hidden" name="fee" value="{{fee}}">
            <input type="hidden" name="final_exchange" value="{{final_exchange}}">
            <button type="submit">Exchange</button>
        </form>
    </main>
    <footer>
        <p>by: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/currency_exchange/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Exchange - Currency Exchange</title>
</head>
<body>
    <header>
        <h1>Currency Exchange</h1>
    </header>
    <main>
    {% if error %}
        <p style="color:red;"><strong>{{ error }}</strong></p>
    {% endif %}
        <h2>Make conversion</h2>
        <form id="exchange" onsubmit="return validate_form()" action="{{ url_for('currencyexchange.exchange_preview') }}" method="post">
            <label for="origin_currency">Origin currency:</label>
            <select id="origin_currency" name="origin_currency" onchange="update_destination_currency_list()">
                <option value="" disabled selected>Select origin currency</option>
                <option value="CLP">Chilean peso</option>
                <option value="ARS">Argentine peso</option>
                <option value="USD">US dollar</option>
                <option value="EUR">Euro</option>
                <option value="TRY">Turkish lire</option>
                <option value="GBP">Great Britain pound</option>
            </select>
            <br />
            <label for="destination_currency">Destination currency:</label>
            <select id="destination_currency" name="destination_currency">
                <option value="" disabled selected>Select destination currency</option>
                <option value="CLP">Chilean peso</option>
                <option value="ARS">Argentine peso</option>
                <option value="USD">US dollar</option>
                <option value="EUR">Euro</option>
                <option value="TRY">Turkish lire</option>
                <option value="GBP">Great Britain pound</option>
            </select>
            <br />
            <label for="amount">Amount:</label>
            <input type="number" id="amount" name="amount" min="0" step="0.01" required>
          
            <button type="submit">Get exchange</button>
          </form>

          {% if exchange_history %}
            <h3>Exchange history</h3>
            <table style="border: 1px solid black;">
                <thead>
                    <tr>
                        <th>Exchange ID</th>
                        <th>Origin currency</th>
                        <th>Destination currency</th>
                        <th>Amount</th>
                        <th>Exchange</th>
                        <th>Fee</th>
                        <th>Final exchange</th>
                    </tr>
                </thead>
                <tbody>
                    {% for exchange in exchange_history %}
                    <tr>
                        <td>{{ exchange.id }}</td>
                        <td>{{ exchange.origin_currency }}</td>
                        <td>{{ exchange.destination_currency }}</td>
                        <td>{{ exchange.amount }}</td>
                        <td>{{ exchange.exchange }}</td>
                        <td>{{ exchange.fee }}</td>
                        <td>{{ exchange.final_exchange }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
    </main>
    <footer>
        <p>by: dlimon.net</p>
    </footer>

<script>
    function update_destination_currency_list() {
        var origin_currency = document.getElementById("origin_currency").value;
        var destination_currency = document.getElementById("destination_currency");
    
        // set all destination currency options to enabled
        for (var i = 0; i < destination_currency.options.length; i++) {
            destination_currency.options[i].disabled = false;
        }
    
        // disable the option that is the same as the origin currency
        for (var i = 0; i < destination_currency.options.length; i++) {
            if (destination_currency.options[i].value === origin_currency) {
                destination_currency.options[i].disabled = true;
                break;
            }
        }
    }

    function validate_form() {
        var origin_currency = document.getElementById("origin_currency").value;
        var destination_currency = document.getElementById("destination_currency").value;
    
        if (origin_currency === destination_currency) {
            alert("Select different currencies so you can make the exchange");
            return false;
        }
    
        if (origin_currency === "" || destination_currency === "") {
            alert("Please select a currency");
            return false;
        }
    
        return true;
    }
    </script>
</body>
</html>

dlimon2_solutions/templates/hello.html
<!DOCTYPE html>
<html>
<head>
    <title>Dev Level Zero - @dlimon2</title>
</head>
<body>
    <header>
        <h1>Dev Level Zero</h1>
        <h3><a href="https://github.com/dlimon2" target="_blank">@dlimon2</a>
    </header>
    <main>
    <ul>
        <li><a href="{{url_for('bankingsystem.hello')}}">BancaDev: Banking System</a>
        <p>Username: daniel | Password: admin | Reset system (flush data): <a href="{{url_for('bankingsystem.reset')}}">/bankingsystem/reset</a></p>
        <li><a href="{{url_for('shippingsystem.hello')}}">ShippingDev: Shipping System</a>
        <p>Username: dani | Password: bob | Reset system (flush data): <a href="{{url_for('shippingsystem.reset')}}">/shippingsystem/reset</a></p>
        <li><a href="{{url_for('currencyexchange.hello')}}">ExchangeDev: Currency Exchange</a>
        <p>Reset system (flush data): <a href="{{url_for('currencyexchange.reset')}}">/currencyexchange/reset</a></p>
        <li><a href="{{url_for('universityenrollment.hello')}}">UniversityDev: University Enrollment</a>
        <p>Username: daniel | Password: admin | <br />
           Username: cj | Password: cj | <br />
            Username: montana | Password: montana | <br />
            Username: adaxoxo | Password: ada | <br />
            Username: perro | Password: perro | <br />
            Reset system (flush data): <a href="{{url_for('universityenrollment.reset')}}">/universityenrollment/reset</a></p>

    </ul>
    </main>
</body>
</html>

dlimon2_solutions/templates/shipping_system/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard - Shipping Dev</title>
</head>
<body>
    <header>
        <h1>Shipping Dev</h1>
    </header>
    <main>
        <h2>Dashboard</h2>
        <p>Welcome, {{username}}!</p>

            <ul>
                <li><a href="{{url_for('shippingsystem.send')}}">Send package</a></li>
            </ul>

        {% if shipping_history %}
        <h3>Shipping history</h3>
        <table style="border: 1px solid black;">
            <thead>
                <tr>
                    <th>Shipping ID</th>
                    <th>Sender</th>
                    <th>Receiver</th>
                    <th>Weight</th>
                    <th>Total Price</th>
                </tr>
            </thead>
            <tbody>
                {% for shipping in shipping_history %}
                <tr>
                    <td>{{ shipping.shipping_id }}</td>
                    <td>{{ shipping.sender }}</td>
                    <td>{{ shipping.receiver }}</td>
                    <td>{{ shipping.weight }}</td>
                    <td>${{ shipping.total_price }}</td>
                    <td>{{ shipping.shipping_status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </main>
    <footer>
        <a href="{{url_for('shippingsystem.logout')}}">Logout</a>
        <p>by: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/shipping_system/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login - Shipping Dev</title>
</head>
<body>
    <header>
        <h1>Shipping Dev</h1>
    </header>
    <main>
        <form action="{{url_for('shippingsystem.login')}}" method="post">
            <label for="shipping_username">Username:</label>
            <input type="text" id="shipping_username" name="shipping_username" required><br><br>
            <label for="shipping_password">Password:</label>
            <input type="shipping_password" id="shipping_password" name="shipping_password" required><br><br>
            <input type="submit" value="Login">
        </form>
    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/shipping_system/send.html
<!DOCTYPE html>
<html>
<head>
    <title>Send package - Shipping Dev</title>
</head>
<body>
    <header>
        <h1>Shipping Dev</h1>
    </header>
    <main>
        <h2>Send a package</h2>
        <form action="{{url_for('shippingsystem.send')}}" method="post">
            <label for="shipping_sender">Sender</label>
            <input type="text" name="shipping_sender" id="shipping_sender" value="{{ sender }}" readonly required>
            <label for="shipping_receiver">Receiver</label>
            <input type="text" name="shipping_receiver" id="shipping_receiver" required>
            <label for="shipping_package_weight">Weight</label>
            <input type="number" name="shipping_package_weight" id="shipping_package_weight" required>
            <input type="submit" value="Preview">
        </form>
        <a href="{{url_for('shippingsystem.dashboard')}}">Back to Dashboard</a>
    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/shipping_system/send_confirmation.html
<!DOCTYPE html>
<html>
<head>
    <title>Send package - Shipping Dev</title>
</head>
<body>
    <header>
        <h1>Shipping Dev</h1>
    </header>
    <main>
        <h2>Send a package</h2>
        
        <div class="shipping-info">
            <h3>Shipping Information Confirmation</h3>
            <ul>
                <li><strong>Shipping ID:</strong> {{ shipping_id }}</li>
                <li><strong>Sender:</strong> {{ sender }}</li>
                <li><strong>Receiver:</strong> {{ receiver }}</li>
                <li><strong>Weight:</strong> {{ weight }}</li>
                <li><strong>Total Price:</strong> {{ total_price }}</li>
            </ul>
        </div>

        <form action="{{url_for('shippingsystem.send_confirmation')}}" method="post">
            <input type="hidden" name="shipping_id" value="{{ shipping_id }}">
            <input type="hidden" name="shipping_sender" value="{{ sender }}">
            <input type="hidden" name="shipping_receiver" value="{{ receiver }}">
            <input type="hidden" name="shipping_package_weight" value="{{ weight }}">
            <input type="hidden" name="shipping_total_price" value="{{ total_price }}">
            <p>Confirm shipping information?</p>
            <input type="submit" value="Confirm">
        </form>

    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/university_enrollment/campus.html
<!DOCTYPE html>
<html>
<head>
    <title>Select campus - DevUniversity</title>
</head>
<body>
    <header>
        <h1>DevUniversity</h1>
    </header>
    <main>
        {% if error %}
            <p style="color: red;">{{error}}</p>
        {% endif %}
        <h2>Select campus</h2>
        <p>Logged in as {{name}} {{last_name}}</p>
        <form action="{{url_for('universityenrollment.enrollment')}}" method="post">
            <table>
                <tr>
                    <th>Campus Name</th>
                    <th>Program</th>
                    <th>Slots available</th>
                    <th>Enroll</th>
                </tr>
                {% for campus in campus_slots %}
                <tr>
                    <td>{{ campus['campus'] }}</td>
                    <td>{{ campus['slots'][0]['program'] }}</td>
                    <td>{{ campus['slots'][0]['slots'] }}</td>
                    <td>
                        {% if campus['slots'][0]['slots'] > 0 %}
                            <form action="{{url_for('universityenrollment.enrollment')}}" method="post">
                                <input type="hidden" name="university_campus" value="{{ campus['campus'] }}">
                                <input type="hidden" name="university_program" value="{{ campus['slots'][0]['program'] }}">
                                <button type="submit">Enroll</button>
                            </form>
                        {% else %}
                            <span style="color: red;">Not Available</span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </table>
        </form>

    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/university_enrollment/enrollment.html
<!DOCTYPE html>
<html>
<head>
    <title>Enrolled! - DevUniversity</title>
</head>
<body>
    <header>
        <h1>DevUniversity</h1>
    </header>
    <main>
        {% if error %}
            <p style="color: red;">{{error}}</p>
        {% endif %}
        <h2>Congratuilations!</h2>
        <p>Your enrollment process is successfully accepted!</p>
        <p>Enrollment details:</p>
        <ul>
            <li>First name: {{name}}</li>
            <li>Last name: {{last_name}}</li>
            <li>Username: {{username}}</li>
            <li>Program: {{program}}</li>
            <li>Campus: {{campus}}</li>
    </main>
    <footer>
        <a href="{{url_for('universityenrollment.logout')}}">Logout</a>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/university_enrollment/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login - DevUniversity</title>
</head>
<body>
    <header>
        <h1>DevUniversity</h1>
    </header>
    <main>
        {% if error %}
            <p style="color: red;">{{error}}</p>
        {% endif %}
        <h2>Login</h2>
        {% if error == 'too many login attempts' %}
            <p style="color: red;">Contact university support.</p>
        {% else %}
        <form action="{{url_for('universityenrollment.login')}}" method="post">
            <label for="university_username">Username:</label>
            <input type="text" id="university_username" name="university_username" required><br><br>
            <label for="university_password">Password:</label>
            <input type="university_password" id="university_password" name="university_password" required><br><br>
            <input type="submit" value="Login">
        </form>
        {% endif %}

    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>

dlimon2_solutions/templates/university_enrollment/programs.html
<!DOCTYPE html>
<html>
<head>
    <title>Select program - DevUniversity</title>
</head>
<body>
    <header>
        <h1>DevUniversity</h1>
    </header>
    <main>
        <p>Logged in as {{name}} {{last_name}}</p>
        {% if error %}
            <p style="color: red;">{{error}}</p>
        {% endif %}
        <h2>Select program</h2>
        <form action="{{ url_for('universityenrollment.campus') }}" method="post">
            <label for="university_program">Program:</label>
            <select id="university_program" name="university_program">
                <option value="computer_science">Computer Science</option>
                <option value="medicine">Medicine</option>
                <option value="marketing">Marketing</option>
                <option value="art">Arts</option>
            </select><br><br>
            <input type="submit" value="Enroll">
    </main>
    <footer>
        <p>dev: dlimon.net</p>
    </footer>
</body>
</html>